name: Sync Repositories

on:
  push:
    branches:
      - main  # adjust branch name if needed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.SOURCE_REPO_OWNER }}/${{ secrets.SOURCE_REPO_NAME }}
          token: ${{ secrets.SOURCE_REPO_TOKEN }} # Replace with personal access token

      - name: Push to destination repository
        run: |
          git config --global user.email "soniyaraibagi@gmail.com"
          git config --global user.name "sr-temp01"
          git push https://github.com/${{ secrets.DESTINATION_REPO_OWNER }}/${{ secrets.DESTINATION_REPO_NAME }}.git HEAD:main --force

